### ISSUE TITLE
Could we use camelCase here?

### ISSUE THREAD

**Issue by fhamon** [DeuxHuitHuit/framework.js-modules#105]
Is there a reason my its `postscroll` and not `postScroll` ?

@nitriques @PascalPiche @beaubbe

https://github.com/DeuxHuitHuit/framework.js-modules/blob/40677ab3900eb97da83812f1fab258b872359de9/src/modules/window-notifier.js#L27

**Comment by nitriques** [comment]
@fhamon all already existing action were lowercase, so it think that's why. Changing that won't add any value.
