### ISSUE TITLE
Add a canonical updater

### ISSUE THREAD

**Issue by hotdoy** [DeuxHuitHuit/framework.js-modules#147]
Browsers native share seems to use canonical instead of current url.
A canonical updater (something like the title-updater) could be a good addition.

**Comment by fhamon** [comment]
We should do a "meta updater" were we config all the nodes we want to change on page.enter and articleChanger.enter

The title and canonical meta should be in that module.

That way, in the future, we can easily add new metas that need to be updated.

**Comment by fhamon** [comment]
> we config all the nodes we want to change

**Comment by PascalPiche** [comment]
I will try to make a proposition Monday to partially unify the concept accross the different modules. It will be a mix of both idea.

**Comment by nitriques** [comment]
@hotdoy  See #149

**Comment by nitriques** [comment]
closed in e9524e2
