### ISSUE TITLE
Add article changer events in alt-language-link-updater

### ISSUE THREAD

**Issue by beaubbe** [DeuxHuitHuit/framework.js-modules#15]
add articleChanger.loaded and articleChanger.enter

**Comment by PascalPiche** [comment]
Seem to be already fixed in the dev Branch

**Comment by nitriques** [comment]
Yup : https://github.com/DeuxHuitHuit/framework.js-modules/commit/80aae067b82c4a3384739e73df6cd26ce1b3db03
