### ISSUE TITLE
No is-playing state in auto-oembed

### ISSUE THREAD

**Issue by beaubbe** [DeuxHuitHuit/framework.js-modules#170]
In auto-oembed, in the playBtnClick function, 

if the oembe dis already loaded, the class "is-playing" will be added to the container which will make it able to hide the thumbnail/play and show the video.

In the same fucntion, if the omebed is not already laoded, it will be loaded but the "is-playing" class will never be added to the cotnainer.

**Comment by nitriques** [comment]
please open a PR @beaubbe

**Comment by nitriques** [comment]
@beaubbe ping

**Comment by nitriques** [comment]
@beaubbe ping pong

**Comment by nitriques** [comment]
@beaubbe ping pong ping pong

**Comment by nitriques** [comment]
Fixed in 922a9468477ddb28204d8cbec59c29d40b9b3526
