### ISSUE TITLE
Use object-fit for background videos 

### ISSUE THREAD

**Issue by fhamon** [DeuxHuitHuit/framework.js-modules#274]
We should use object-fit: cover|contain|ect for resizing videos. It will remove a lot of js code and the necessity of using those js modules/com only for background videos.

@nitriques @PascalPiche What do you guys think ?

**Comment by fhamon** [comment]
Note that object-fit is not supported by ie11. But I don't think it should restrain ourself of using it.

**Comment by nitriques** [comment]
I am all up for it

**Comment by fhamon** [comment]
We good. https://github.com/DeuxHuitHuit/framework.js-modules/pull/298
