### ISSUE TITLE
Problem in _getNextRouteFromData with error pages

### ISSUE THREAD

**Issue by beaubbe** [DeuxHuitHuit/framework.js-modules#33]
A error page only has 1 route regardless of how many language there is. So, when trying to find the route for any other language than the main one, it will not find anything. Here is a fix.

var result = data.page.routes()[0];

```
    if (data.page.routes().length > 1) {
        result = data.page.routes()[_getLanguageIndex()];
    }

    return result;
```

**Comment by nitriques** [comment]
Can you send a PR please ?
