### ISSUE TITLE
Remove ga from the jQuery namespace

### ISSUE THREAD

**Issue by nitriques** [DeuxHuitHuit/framework.js-modules#6]

**Comment by fhamon** [comment]
I propose `window.sendEvent` or `App.sendEvent`

not a fan of putting it into App namespace tho.

**Comment by nitriques** [comment]
I think we should convert it to `App.fx.notify('ga.sendEvent', ...)`. That way, we will be able to properly load the right version (dev or not)

**Comment by nitriques** [comment]
Fixed in 66fd0074901411a17b254daeac3ad84af5d90369
